version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot
    volumes:
      - .:/app
    env_file:
      - .env
    command: ["bash", "run.sh"]
    ports:
      - "8000:8000"  # для IPN
    restart: always


  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your NGINX configuration file
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
    ports:
      - "8081:80"
      - "443:443"
    depends_on:
      - web  # Ensure web service is up before NGINX starts
